/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author João Marcos
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    protected static JanelaEscola jEscola;
    protected static JanelaCurso jCurso;
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAreaTrabalho = new javax.swing.JDesktopPane();
        menuSuperior = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();
        menuCadastros = new javax.swing.JMenu();
        menuItemEscolas = new javax.swing.JMenuItem();
        menuItemCursos = new javax.swing.JMenuItem();
        menuItemTurmas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemFuncionarios = new javax.swing.JMenuItem();
        menuItemAlunos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemPerfis = new javax.swing.JMenuItem();
        menuItemUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Registros de Merendas");
        setExtendedState(MAXIMIZED_BOTH);

        painelAreaTrabalho.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout painelAreaTrabalhoLayout = new javax.swing.GroupLayout(painelAreaTrabalho);
        painelAreaTrabalho.setLayout(painelAreaTrabalhoLayout);
        painelAreaTrabalhoLayout.setHorizontalGroup(
            painelAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        painelAreaTrabalhoLayout.setVerticalGroup(
            painelAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemSair);

        menuSuperior.add(menuArquivo);

        menuCadastros.setText("Cadastros");

        menuItemEscolas.setText("Escolas");
        menuItemEscolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEscolasActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemEscolas);

        menuItemCursos.setText("Cursos");
        menuItemCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCursosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemCursos);

        menuItemTurmas.setText("Turmas");
        menuCadastros.add(menuItemTurmas);
        menuCadastros.add(jSeparator1);

        menuItemFuncionarios.setText("Funcionários");
        menuCadastros.add(menuItemFuncionarios);

        menuItemAlunos.setText("Alunos");
        menuCadastros.add(menuItemAlunos);
        menuCadastros.add(jSeparator2);

        menuItemPerfis.setText("Perfis");
        menuCadastros.add(menuItemPerfis);

        menuItemUsuarios.setText("Usuários");
        menuCadastros.add(menuItemUsuarios);

        menuSuperior.add(menuCadastros);

        setJMenuBar(menuSuperior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAreaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAreaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        //Fechar o sistema - Fechar JanelaPrincipal
        this.dispose();
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemEscolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEscolasActionPerformed
        
        //Verifica se a janelaEscola já existe
        if(jEscola == null)
        {
            //Instancia a janela e adiciona no DesktopPanel
            jEscola = new JanelaEscola();
            painelAreaTrabalho.add(jEscola);
            painelAreaTrabalho.getDesktopManager().maximizeFrame(jEscola); //abre a janela interna maximizada
            jEscola.setVisible(true);
        }
        else
        {
            //Se já está instanciada, apenas move para frente
            jEscola.moveToFront();
        }

    }//GEN-LAST:event_menuItemEscolasActionPerformed

    private void menuItemCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCursosActionPerformed
        //Verifica se a janelaCurso já existe
        if(jCurso == null)
        {
            //Instancia a janela e adiciona no DesktopPanel
            jCurso = new JanelaCurso();
            painelAreaTrabalho.add(jCurso);
            painelAreaTrabalho.getDesktopManager().maximizeFrame(jCurso);
            jCurso.setVisible(true);
        }
        else
        {
            //Se já está instanciada, apenas move para frente
            jCurso.moveToFront();
        }
    }//GEN-LAST:event_menuItemCursosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuItemAlunos;
    private javax.swing.JMenuItem menuItemCursos;
    private javax.swing.JMenuItem menuItemEscolas;
    private javax.swing.JMenuItem menuItemFuncionarios;
    private javax.swing.JMenuItem menuItemPerfis;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemTurmas;
    private javax.swing.JMenuItem menuItemUsuarios;
    private javax.swing.JMenuBar menuSuperior;
    private javax.swing.JDesktopPane painelAreaTrabalho;
    // End of variables declaration//GEN-END:variables

}
